version: '3' 
services:
  webstorm-vnc-docker:
    image: openkbs/webstorm-vnc-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webstorm-vnc-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - .env
    ports:
      - 5901:5901
      - 6901:5601
    volumes:
    volumes:
      - ./WebstormProjects:/home/developer/WebstormProjects
      - ./.WebstormIC2020.3:/home/developer/.WebstormIC2020.3
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace
      - ./.java:/home/developer/.java
